//Code Generated by GPT

import "dotenv/config";
import nodemailer from "nodemailer";
import sqlite3 from "sqlite3";
import { open } from "sqlite";

// Async function to send an email
async function sendEmail() {
  // Open the SQLite database
  const db = await open({
    filename: "customers.db",
    driver: sqlite3.Database,
  });

  try {
    // Retrieve the first customer's email
    const row = await db.get("SELECT email FROM customers LIMIT 1");

    if (!row) {
      console.error("No customers found in the database.");
      return;
    }

    let recipientEmail = row.email;
    console.log("Sending email to:", recipientEmail);

    // Create the email transporter
    let transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // Email options
    let mailOptions = {
      from: process.env.EMAIL_USER,
      to: recipientEmail, // Retrieved from database
      subject: "WE SMOKED OUT",
      text: "HEY MAMA BEN!!",
    };

    // Send the email
    let info = await transporter.sendMail(mailOptions);
    console.log("Email sent:", info.response);
  } catch (error) {
    console.error("Error:", error);
  } finally {
    await db.close(); // Close the database connection
  }
}

// Call the function
sendEmail();
